# Generated by Django 3.1.4 on 2024-02-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_auto_20240205_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
