# Generated by Django 3.1.4 on 2024-02-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_lesson_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course_app.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seaons', to='course_app.course'),
        ),
    ]
